config/routes.rb
Rails.application.routes.draw do
  root 'maps#show'
  get '/maps' => 'maps#show'
  
  resources :places
  resources :trips

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/current_trip.rb
module CurrentTrip

    private

    def set_trip
        @trip = Trip.find(session[:trip_id])
    rescue ActiveRecord::RecordNotFound
        @trip = Trip.create
        session[:id] = @trip.id
    end
    
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :trips_origin, class_name: 'Trip', foreign_key: 'origin_id'
  has_many :trips_destination, class_name: 'Trip', foreign_key: 'destination_id'

  # def address
  #   [street, city, state, zip].compact.join(', ')
  # end

  # def address_changed?
  #   street_changed? || city_changed? || zip_changed? || state_changed?
  # end

  def trips
    (trips_origin + trips_destination).uniq
  end
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
end

app/models/trip.rb
# frozen_string_literal: true

class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :origin, class_name: 'Place'
  belongs_to :destination, class_name: 'Place'
  before_save :set_distance

  def set_distance
    self.distance = origin.distance_to(destination)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :trips
  has_many :services

  def as_a(role)
    role = Role.find_by(name: role) if role.class == String
    user_roles.find_by(role: role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    # include CurrentTrip
    # before_action :set_trip
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def show
    @place = Place.new(address: search_address)
  end

  private
 
  def search_address
    params[:address]
    
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  
  def new
    @place = Place.new
  end


  def show
    @place = Place.find(params[:id])
  end

  def create
    # TODO: if called from trips
    # 1) populate name field
    # 2) redirect back to trip create or back
    @place = Place.new(place_params)
    redirect_to maps_path if @place.save
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def place_params
    params.require(:place).permit(:name, :street, :city, :state, :zip, :address)
  end
end

app/controllers/trips_controller.rb
# frozen_string_literal: true

class TripsController < ApplicationController
  before_action :authenticate_user!

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:id]) if params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trip_params
    params.fetch(:trip, {}).permit(:origin_id, :destination_id, :place_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        services = Service.where(proviser: auth.provider, uid: auth.uid).first

        if service.present?
            user = service.user
            service.update(
                expires_at: Time.at(auth.credentials.expires_at),
                access_token: auth.credentials.token,
            )
        
        else
            user= User.create(
                email: auth.info.email,
                password: Devise.friendly_token[0,20]
            )
            user.services.create(
                provider: auth.provider,
                uid: auth.uid,
                expires_at: Time.at(auth.credentials.expires_at),
                access_token: auth.credentials.token,
            )
        end

        sign_in_and_redirect user, event: :authentication
        set_flash_message :notice, :success, kind: "Facebook"
    end

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/trip_helper.rb
module TripHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_messages.html.erb
<%if notice %>
  <div class='alert alert-info'>
    <%= notice %>
  </div>
<%end%>
<%if alert %>
  <div class='alert alert-warning'>
    <%= alert %>
  </div>
<%end%>

app/views/application/_navbar.html.erb
<!-- !NAVIGATION START-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Commuter</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- Logout Sign Up/Login-->
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to current_user.email, edit_user_registration_path  %>
        <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        <%else%>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path %>
          </li>
        <%end%>
      </ul>
      <!-- Logout Sign Up/Login-->
    </div>
  </div>
</nav>
<!-- !NAVIGATION END-->

app/views/application/_search_places.html.erb
<h1>Search Panal</h1>
<%= form_with model: @place do |form| %>
  <%= form.text_field :address %>
  <%= form.submit("Search") %>
<% end %>

app/views/application/_sidebar.html.erb
<div class='sidebar'>
  <%= render 'search_places'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name='turbolinks-visit-control' content='reload'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['google_maps_api_key']}", "application", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>
  <body>
    <%= render 'messages' %>
    <div class='page_content'>
      <%= render 'navbar' %>
      <section>
        <%= render 'sidebar' %>
        <%= yield() %>
      </section>
    </div>
  </body>
</html>

app/views/maps/show.html.erb
<h1>maps</h1>
<%= tag.div nil, id: "map" %>

app/views/places/_form.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMap2);
    </script>
<% end %>

<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

    <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

    <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <p>
    <div id="map2"></div>
  </p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Places</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><button class="btn btn-primary btn-sm"><%= link_to 'Show', place %></button></td>
        <td><button class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_place_path(place) %></button></td>
        <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<%= will_paginate @places %>
</div>
<div class="col">
  <%= tag.div nil, id: "map", data: {places: @places.to_json(methods: [:address]) } %>
  
</div>
<br>
<button class="btn btn-success"><%= link_to 'New Place', new_place_path %></button>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>
      <ul>
        <% trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <%= form.label :origin %>
      <%= form.collection_select :origin_id, @places, :id, :name, selected: @place_id %>
    </div>
    <div class="field">
      <%= form.label :destination %>
      <%= form.collection_select :destination_id, @places, :id, :name, selected: @place_id %>
    </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Trips</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%=trip.origin.name%></td>
        <td><%=trip.destination.name%></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>
<div>Origin: <%=@trip.origin.name%></div>
<div> Destination: <%=@trip.destination.name%></div>
<div>Distance: <%=@trip.distance%></div>

<div class="col">
  <%= tag.div nil, id: "map2", data: {places: [@trip.origin, @trip.destination].to_json(methods: [:address]), origin: @trip.origin.to_json(methods: [:address]), destination: @trip.destination.to_json(methods: [:address]) } %>
</div>
<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>